<?php

/**
 *
 */
function broadsoft_lost_password_init() {
  // module_load_include(file type, module name, typeless file name);
  module_load_include('php', 'broadsoft_account_request', '/PHPMailer/PHPMailerAutoload');
}

/**
   * Implement hook_form_alter() to change the behaviour of password reset form.
 */
function broadsoft_lost_password_form_user_pass_alter(&$form, &$form_state) {
  // Override the submit to send the email using PHP mailer
  $form['#submit'][0] = 'broadsoft_lost_password_user_pass_submit';
}

function broadsoft_lost_password_user_pass_submit(&$form, &$form_state) {
  $account = $form_state['values']['account'];
  // Mail one time login URL and instructions using current language.
  $params['account'] = $account;
  $language = $language ? $language : user_preferred_language($account);
  // DO not send the email but build the message
  $mail = drupal_mail('user', 'password_reset', $account->mail, $language, $params, FALSE);

  // from broadsoft_user_management
  if( ($mail['id'] != 'user_password_reset') || empty($mail['subject']) ) {
    watchdog('mail', 'Cannot build mail', array('Type' => 'Password Reset'), WATCHDOG_ERROR);
    return;
  }
  SendSMTPMail($mail['subject'], $mail['body'], $mail['to'], '', 'xchangesupport@broadsoft.com');
  drupal_set_message('Further instructions have been sent to your email address.');
}





?>